services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "0.0.0.0:9000:9000"
      - "0.0.0.0:9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "0.0.0.0:27017:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    build: .
    container_name: airflow
    restart: always
    env_file: .env
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_DB}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./spark_jobs:/opt/airflow/spark_jobs
      - ./.env:/opt/airflow/.env
    command: >
      bash -c "airflow db init &&
      airflow users create --username $$AIRFLOW_USER --password $$AIRFLOW_PASSWORD --firstname Admin --lastname User --role Admin --email $$AIRFLOW_EMAIL &&
      airflow scheduler &
      exec airflow webserver"

volumes:
  mongo_data:
  postgres_data: